import type { BlockType } from 'vise-workflow-engine/frontend';

export const blockTypes: BlockType[] = [
  {
    id: 'start',
    label: 'Start',
    icon: '🟢',
    color: 'bg-green-100 border-green-300 text-green-800',
    description: 'Entry point of the workflow',
    nodeType: 'standard',
  },
  {
    id: 'manual_review',
    label: 'Manual Review',
    icon: '👁️',
    color: 'bg-blue-100 border-blue-300 text-blue-800',
    description: 'A human reviews the item',
    nodeType: 'standard',
  },
  {
    id: 'auto_classify',
    label: 'Auto Classify',
    icon: '🤖',
    color: 'bg-cyan-100 border-cyan-300 text-cyan-800',
    description: 'AI classifies the item automatically',
    nodeType: 'standard',
  },
  {
    id: 'send_email',
    label: 'Send Email',
    icon: '📧',
    color: 'bg-indigo-100 border-indigo-300 text-indigo-800',
    description: 'Send a notification email',
    nodeType: 'standard',
  },
  {
    id: 'needs_approval',
    label: 'Needs Approval?',
    icon: '❓',
    color: 'bg-yellow-100 border-yellow-300 text-yellow-800',
    description: 'Decision: approve or reject',
    nodeType: 'decision',
  },
  {
    id: 'escalate_or_close',
    label: 'Escalate or Close?',
    icon: '⚖️',
    color: 'bg-orange-100 border-orange-300 text-orange-800',
    description: 'Decision: escalate or close the case',
    nodeType: 'decision',
  },
  {
    id: 'resolved',
    label: 'Resolved',
    icon: '✅',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-800',
    description: 'Successfully resolved',
    nodeType: 'terminal',
  },
  {
    id: 'rejected',
    label: 'Rejected',
    icon: '❌',
    color: 'bg-red-100 border-red-300 text-red-800',
    description: 'Rejected / denied',
    nodeType: 'terminal',
  },
];

export const hookTypes: BlockType[] = [
  {
    id: 'send_slack_alert',
    label: 'Slack Alert',
    icon: '💬',
    color: 'bg-purple-100 border-purple-300 text-purple-800',
    description: 'Send a notification to Slack',
    nodeType: 'hook',
    trigger: 'on_node_entry',
  },
  {
    id: 'log_transition',
    label: 'Log Transition',
    icon: '📝',
    color: 'bg-gray-100 border-gray-300 text-gray-800',
    description: 'Log every state transition to the audit trail',
    nodeType: 'hook',
    trigger: 'on_transition',
  },
  {
    id: 'escalation_detector',
    label: 'Escalation Detector',
    icon: '🚨',
    color: 'bg-rose-100 border-rose-300 text-rose-800',
    description: 'AI detects if the conversation is escalating',
    nodeType: 'hook',
    trigger: 'on_message',
  },
  {
    id: 'sla_timer',
    label: 'SLA Timer',
    icon: '⏱️',
    color: 'bg-amber-100 border-amber-300 text-amber-800',
    description: 'Start an SLA countdown when entering a node',
    nodeType: 'hook',
    trigger: 'on_node_entry',
  },
];
